import { clusterData } from '../mockData';

export function generatePulseMarkdown(weeks: number = 12): string {
  const dateStr = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  let md = `# 📊 Groww App Review Insights Analyser: Weekly Pulse\n`;
  md += `**Date:** ${dateStr}\n`;
  md += `**Scope:** Last ${weeks} Weeks (App Store & Play Store)\n`;
  md += `**Reviews Analysed:** 4,280\n\n`;
  md += `---\n\n`;

  md += `## 📝 Executive Summary\n`;
  md += `This week, user sentiment remained largely stable with a slight positive shift (+2%) driven by the recent Portfolio UI update. However, critical friction remains in the onboarding flow due to prolonged KYC verification times. App stability during market open continues to be the highest severity issue.\n\n`;

  md += `## 🎯 Top Themes & Verbatim Insights\n\n`;

  // Filter top 3 clusters to mock the Weekly Pulse selection
  const topClusters = clusterData.slice(0, 3);

  topClusters.forEach((cluster, index) => {
    md += `### ${index + 1}. ${cluster.emoji} ${cluster.name} (${cluster.percentage}% Volume)\n`;
    md += `**Sentiment:** ${cluster.sentiment}\n\n`;
    md += `*Real User Quotes:*\n`;
    cluster.quotes.forEach(quote => {
      md += `> "${quote}"\n`;
    });
    md += `\n`;
  });

  md += `---\n\n`;
  
  md += `## 🚀 Actionable Next Steps\n\n`;
  md += `1. **Engineering:** Investigate server scaling or caching mechanisms specifically for the 9:15 AM - 9:30 AM load spike to prevent session timeouts.\n`;
  md += `2. **Product & Ops:** Audit the current KYC pipeline; identify the bottleneck causing the 4-day delay and implement an automatic fallback for Aadhaar failures.\n`;
  md += `3. **Design:** Capitalize on the positive reception of the dark mode UI by applying similar aesthetic principles to the Options Trading screen.\n\n`;

  md += `---\n`;
  md += `*Automatically generated by Groww App Review Insights Analyser v2.0*`;

  return md;
}
